# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	bsdinstaller
PORTVERSION=	19.3
#PORTREVISION=	0 # GH_TAGNAME
CATEGORIES=	sysutils

MAINTAINER=	project@opnids.io
COMMENT=	BSD Installer mega-package

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	cpdup:sysutils/cpdup

USE_LDCONFIG=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	opnids
#GH_TAGNAME=	56e41c1

.include <bsd.port.mk>
